name: Compile & Run Smart Contract Unit Tests

on:
  workflow_dispatch:
jobs:
  test:
    name: Build Project
    runs-on: ubuntu-latest
    environment: testing-keys
    env:
      MNEMONIC_KEY: ${{ secrets.MNEMONIC_KEY }}
      ALCHEMY_MAINNET_KEY: ${{ secrets.ALCHEMY_MAINNET_KEY }}
      ALCHEMY_RINKEBY_KEY: ${{ secrets.ALCHEMY_RINKEBY_KEY }}
      ALCHEMY_ROPSTEN_KEY: ${{ secrets.ALCHEMY_ROPSTEN_KEY }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      CMC_KEY: ${{ secrets.CMC_KEY }}
      GAS_PRICE_GWEI_KEY: 20
      GAS_WEI_KEY: 2500000
      ADDRESS_COUNT_KEY: 20
      DEFAULT_ADDRESS_INDEX_KEY: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Compiling Smart Contracts
        run: |
          yarn compile
      - name: Executing Tests
        run: |
          yarn test
